# This file is based on https://github.com/WebGoat/WebGoat/blob/develop/docker-compose.yml

version: '3.5'

services:

  webgoat:
    image: webgoat/webgoat-8.0:v8.0.0.M25
    environment:
      - WEBWOLF_HOST=localhost
      - WEBWOLF_PORT=9090
    ports:
      - "8082:8080"
      - "9002:9001"
    volumes:
      - ./data/webgoat:/home/webgoat/.webgoat-8.0.0.M25
  
  webwolf:
    image: webgoat/webwolf:v8.0.0.M25
    ports:
      - "8083:9090"
    command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
