version: "3.5"

services: 
    node:
        build: ./docker/node
        container_name: node-web
        volumes:
            - ./data/node:/app
        environment:
            - NODE_ENV=development
        working_dir: /app
        ports:
            - "8083:8080"
        networks:
            node-backend:
                ipv4_address: 172.3.0.2
                
networks:
    node-backend:
        driver: bridge
        ipam:
            config:
                - subnet: 172.3.0.0/24