version: '3.5'

services:
  web:
    image: php:5.6-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/hgfs/pentest_set:/var/www/html
    networks:
      pentest-network:
        ipv4_address: 172.20.0.5
    depends_on:
      - mysql

  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      pentest-network:
        ipv4_address: 172.20.0.6

networks:
  pentest-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
