version: '3.5'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /mnt/hgfs/pentest_set:/var/www/html
    networks:
      pentest-network:
        ipv4_address: 172.20.0.5
    depends_on:
      - mysql
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      pentest-network:
        ipv4_address: 172.20.0.6

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "50000:80"
    networks:
      pentest-network:
        ipv4_address: 172.20.0.100

  smtp:
    image: namshi/smtp
    ports:
      - "25:25"
    networks:
      pentest-network:
        ipv4_address: 172.20.0.7

networks:
  pentest-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
