version: '3'
services:
  web:
    image: php:5.6-apache
    ports:
      - "80:80"
    command: >
      bash -c "chown -R www-data:www-data /var/www/html &&
               apache2-foreground"
    volumes:
      - /mnt/hgfs/pentest_set:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
